#!/bin/bash

DIR=$(dirname $(/usr/local/bin/realpath $0))

LATLONG="51.5074N 0.1278W"
LAT=$(echo $LATLONG | cut -d' ' -f1)
LONG=$(echo $LATLONG | cut -d' ' -f2)


$DIR/packages/sunwait/sunwait poll $LAT $LONG
DAYLIGHT_CODE=$?

if [ $DAYLIGHT_CODE == 2 ]; then
  # day
  MODE="day"
  BRIGHTNESS=0.8
elif [ $DAYLIGHT_CODE == 3 ]; then
  # night
  MODE="night"
  BRIGHTNESS=0.55
fi

$DIR/packages/brightness/brightness $BRIGHTNESS

echo "$(date +%Y-%m-%dT%H:%M:%SZ%z) $BRIGHTNESS $MODE"
